### ISSUE TITLE
Ajouter le lien vers la fiche CIQUAL

### ISSUE THREAD

**Issue by martinregner** [datagir/agribalyse#42]
L'objectif serait de mieux relier les deux bases.

Serait-il possible d'ajouter sur chaque fiche, le lien vers la fiche CIQUAL du même produit ?
Au clic sur le code (ou sur CIQUAL), ex. pour [une pizz](https://agribalyse.ademe.fr/app/aliments/25435#Pizza_jambon_fromage) :

> Code Ciqual : [25435](https://ciqual.anses.fr/#/aliments/25435)

L'URL pour les fiches CIQUAL est toujours https://ciqual.anses.fr/#/aliments/CODECIQUAL

(comme ça tu auras pas mis le lien CIQUAL sur la fiche pour rien ;))

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
top, merci ! 👍
