### ISSUE TITLE
Mise à jour de la base

### ISSUE THREAD

**Issue by martinregner** [datagir/agribalyse#45]
La nouvelle version des données a été mise en ligne : https://data.ademe.fr/datasets?topics=TQJGtxm2_
Au-delà de la mise à jour des FE, il y a : 

- [x] ⚠️ **Un changement dans les unité**s : pour éviter les "E-06", "E-03" ... etc. pas du tout homogène dans les unités, ils ont tous été retirés. Les virgules sont désormais reléguées dans les données

![image](https://user-images.githubusercontent.com/46482115/208164801-306a805f-3ac0-4603-a11a-fa63fecd6e59.png)

donc :
![image](https://user-images.githubusercontent.com/46482115/208165388-86ac4ca4-6fd7-4018-998f-8f7654acb032.png)
devient :
![image](https://user-images.githubusercontent.com/46482115/208165224-09ee43ab-52ae-4611-8e05-8e0b555e9195.png)

---

- [x] **Deux nouvelles colonnes à ajouter** : 
  - Effets toxicologiques sur la santé humaine : substances non-cancérogènes
  - Effets toxicologiques sur la santé humaine : substances cancérogènes

En bas :
![image](https://user-images.githubusercontent.com/46482115/208162567-90d7bff9-9937-4d0c-83c7-3d79038a90c5.png)

Il faut ajouter une popup (?) avec ce texte : 
`Ces indicateurs représentent l’impact sur la santé lié à l’exposition de la population générale aux contaminants chimiques via les pollutions du milieu (air, eau, sol).  Ces contaminants émis dans l’environnement sont notamment des pesticides, des métaux lourds ou encore des polluants industriels. L’exposition par ingestion directe d’un aliment contenant des résidus de pesticides n’est pour l’instant pas intégrée dans les calculs d’Analyse du Cycle de Vie. Cette exposition est par ailleurs encadrée par la réglementation « Limites Maximales de Résidus (LMR) » au niveau français et européen.  `

@florianpanchout tu me dis si tout n'est pas clair !

**Comment by florianpanchout** [comment]
Done. C'est visible ici : https://deploy-preview-46--agribalyse.netlify.app/

**Comment by martinregner** [comment]
Ok top !
Est-ce que tu pourrais juste corriger le titre en _Explorer la base Agribalyse **3.1**_ ? :)

**Comment by florianpanchout** [comment]
C'est en prod :)
